export type WineRegion =
  | "Bordeaux"
  | "Burgundy"
  | "Piedmont"
  | "Tuscany"
  | "Champagne"
  | "Napa Valley";

export type WineCollection = "Old World" | "New World" | "Sommelier's Selection" | "Collector's Cellar";

export interface Wine {
  id: string;
  producer: string;
  name: string;
  vintage: number;
  region: WineRegion;
  country: string;
  grape: string;
  bottleSize: string;
  price: number;
  costPrice: number;
  quantity: number;
  reorderAt: number;
  storage: string;
  supplier: string;
  collections: WineCollection[];
  pairing: string;
  tasting: string;
  sommelier: string;
  collector?: boolean | undefined;
}

export const wineRegions: { region: WineRegion; blurb: string }[] = [
  { region: "Bordeaux", blurb: "Prestige Bordeaux selections from the Left and Right Bank." },
  { region: "Burgundy", blurb: "Grand Cru and Premier Cru selections of quiet precision." },
  { region: "Piedmont", blurb: "Barolo and Barbaresco of structure, perfume and patience." },
  { region: "Tuscany", blurb: "Brunello di Montalcino and Super Tuscan selections." },
  { region: "Champagne", blurb: "Prestige cuvées for celebration and for the table." },
  { region: "Napa Valley", blurb: "Premium Cabernet Sauvignon of depth and polish." },
];

export const wines: Wine[] = [
  {
    id: "w-laf-82",
    producer: "Château Lafite Rothschild",
    name: "Pauillac Premier Grand Cru Classé",
    vintage: 1982,
    region: "Bordeaux",
    country: "France",
    grape: "Cabernet Sauvignon · Merlot",
    bottleSize: "750ml",
    price: 9800000,
    costPrice: 7400000,
    quantity: 0,
    reorderAt: 1,
    storage: "Collector vault · Bay A1",
    supplier: "Négociant allocation",
    collections: ["Old World", "Collector's Cellar"],
    collector: true,
    pairing: "Dry-aged beef, truffle, aged hard cheeses.",
    tasting: "Cedar, graphite, dried cassis and tobacco leaf; long, fine-grained finish.",
    sommelier:
      "A landmark vintage. Offered as a collector's selection — subject to availability and vintage verification before service.",
  },
  {
    id: "w-margaux-15",
    producer: "Château Margaux",
    name: "Margaux Premier Grand Cru Classé",
    vintage: 2015,
    region: "Bordeaux",
    country: "France",
    grape: "Cabernet Sauvignon blend",
    bottleSize: "750ml",
    price: 3450000,
    costPrice: 2600000,
    quantity: 3,
    reorderAt: 2,
    storage: "Cellar · Bay B2",
    supplier: "Vinum Imports Lagos",
    collections: ["Old World", "Sommelier's Selection"],
    pairing: "Rack of lamb, wild mushroom, aged Comté.",
    tasting: "Violet, blackcurrant and crushed stone with silken tannin.",
    sommelier: "Elegant rather than powerful. Decant ninety minutes before service.",
  },
  {
    id: "w-pichon-16",
    producer: "Château Pichon Baron",
    name: "Pauillac Deuxième Cru",
    vintage: 2016,
    region: "Bordeaux",
    country: "France",
    grape: "Cabernet Sauvignon · Merlot",
    bottleSize: "750ml",
    price: 780000,
    costPrice: 560000,
    quantity: 9,
    reorderAt: 4,
    storage: "Cellar · Bay B3",
    supplier: "Vinum Imports Lagos",
    collections: ["Old World"],
    pairing: "Grilled ribeye, oxtail, mature cheeses.",
    tasting: "Dark berry, cigar box and cocoa with a firm, polished frame.",
    sommelier: "Our most requested Bordeaux by the bottle at dinner.",
  },
  {
    id: "w-drc-echezeaux-17",
    producer: "Domaine Jean Grivot",
    name: "Échezeaux Grand Cru",
    vintage: 2017,
    region: "Burgundy",
    country: "France",
    grape: "Pinot Noir",
    bottleSize: "750ml",
    price: 1650000,
    costPrice: 1250000,
    quantity: 2,
    reorderAt: 2,
    storage: "Cellar · Bay C1",
    supplier: "Bourgogne Selection",
    collections: ["Old World", "Sommelier's Selection"],
    pairing: "Duck breast, guinea fowl, earthy mushroom dishes.",
    tasting: "Red cherry, rose petal and forest floor; weightless length.",
    sommelier: "Serve slightly cool, 15°C, in a Burgundy bowl.",
  },
  {
    id: "w-meursault-20",
    producer: "Domaine Ballot-Millot",
    name: "Meursault Premier Cru Les Charmes",
    vintage: 2020,
    region: "Burgundy",
    country: "France",
    grape: "Chardonnay",
    bottleSize: "750ml",
    price: 690000,
    costPrice: 500000,
    quantity: 7,
    reorderAt: 3,
    storage: "Cellar · Bay C4 (white)",
    supplier: "Bourgogne Selection",
    collections: ["Old World"],
    pairing: "Butter-poached lobster, roast chicken, aged Gruyère.",
    tasting: "Hazelnut, white peach and citrus oil over a saline core.",
    sommelier: "Our house choice for the tasting menu's seafood course.",
  },
  {
    id: "w-barolo-monfortino-13",
    producer: "Giacomo Conterno",
    name: "Barolo Riserva Monfortino",
    vintage: 2013,
    region: "Piedmont",
    country: "Italy",
    grape: "Nebbiolo",
    bottleSize: "750ml",
    price: 4200000,
    costPrice: 3200000,
    quantity: 1,
    reorderAt: 1,
    storage: "Collector vault · Bay A3",
    supplier: "Piemonte Fine Wine",
    collections: ["Old World", "Collector's Cellar"],
    collector: true,
    pairing: "Braised beef cheek, white truffle, aged Parmigiano.",
    tasting: "Tar, dried rose, sour cherry and liquorice; monumental structure.",
    sommelier: "Decant three hours. One bottle in the vault — reserve in advance.",
  },
  {
    id: "w-barolo-cannubi-18",
    producer: "Damilano",
    name: "Barolo Cannubi",
    vintage: 2018,
    region: "Piedmont",
    country: "Italy",
    grape: "Nebbiolo",
    bottleSize: "750ml",
    price: 520000,
    costPrice: 370000,
    quantity: 12,
    reorderAt: 5,
    storage: "Cellar · Bay D1",
    supplier: "Piemonte Fine Wine",
    collections: ["Old World"],
    pairing: "Ragù, roast veal, hard alpine cheeses.",
    tasting: "Rose, red plum and anise with fine, insistent tannin.",
    sommelier: "The approachable way into Barolo — beautiful with our short rib.",
  },
  {
    id: "w-brunello-16",
    producer: "Biondi-Santi",
    name: "Brunello di Montalcino",
    vintage: 2016,
    region: "Tuscany",
    country: "Italy",
    grape: "Sangiovese",
    bottleSize: "750ml",
    price: 1150000,
    costPrice: 850000,
    quantity: 4,
    reorderAt: 2,
    storage: "Cellar · Bay D3",
    supplier: "Toscana Direct",
    collections: ["Old World", "Sommelier's Selection"],
    pairing: "Bistecca, wild boar, tomato-rich braises.",
    tasting: "Sour cherry, blood orange, dried herb and iron.",
    sommelier: "Classical and long-lived. Decant one hour.",
  },
  {
    id: "w-sassicaia-19",
    producer: "Tenuta San Guido",
    name: "Sassicaia Bolgheri",
    vintage: 2019,
    region: "Tuscany",
    country: "Italy",
    grape: "Cabernet Sauvignon · Cabernet Franc",
    bottleSize: "750ml",
    price: 980000,
    costPrice: 720000,
    quantity: 6,
    reorderAt: 3,
    storage: "Cellar · Bay D4",
    supplier: "Toscana Direct",
    collections: ["Old World"],
    pairing: "Grilled lamb, peppered beef, mature pecorino.",
    tasting: "Cassis, bay leaf, graphite and Mediterranean scrub.",
    sommelier: "The Super Tuscan benchmark; generous even in youth.",
  },
  {
    id: "w-krug-gc",
    producer: "Krug",
    name: "Grande Cuvée Édition 171",
    vintage: 2015,
    region: "Champagne",
    country: "France",
    grape: "Pinot Noir · Chardonnay · Meunier",
    bottleSize: "750ml",
    price: 890000,
    costPrice: 640000,
    quantity: 10,
    reorderAt: 4,
    storage: "Cellar · Champagne cabinet",
    supplier: "Maison Distribution",
    collections: ["Old World", "Sommelier's Selection"],
    pairing: "Oysters, caviar, roast poultry, aged Comté.",
    tasting: "Brioche, candied citrus, hazelnut and a fine, persistent mousse.",
    sommelier: "Our default celebration pour, and excellent through a whole meal.",
  },
  {
    id: "w-dp-13",
    producer: "Dom Pérignon",
    name: "Vintage Brut",
    vintage: 2013,
    region: "Champagne",
    country: "France",
    grape: "Chardonnay · Pinot Noir",
    bottleSize: "750ml",
    price: 620000,
    costPrice: 440000,
    quantity: 14,
    reorderAt: 6,
    storage: "Cellar · Champagne cabinet",
    supplier: "Maison Distribution",
    collections: ["Old World"],
    pairing: "Seafood, sushi, light poultry, celebration service.",
    tasting: "White flower, almond and lemon confit; taut and precise.",
    sommelier: "Requested most often for suite arrivals and anniversaries.",
  },
  {
    id: "w-opus-19",
    producer: "Opus One",
    name: "Napa Valley Red",
    vintage: 2019,
    region: "Napa Valley",
    country: "United States",
    grape: "Cabernet Sauvignon blend",
    bottleSize: "750ml",
    price: 1350000,
    costPrice: 990000,
    quantity: 5,
    reorderAt: 2,
    storage: "Cellar · Bay E1",
    supplier: "New World Cellars",
    collections: ["New World", "Sommelier's Selection"],
    pairing: "Dry-aged steak, smoked short rib, dark chocolate desserts.",
    tasting: "Blackberry, mocha, sweet spice and velvet tannin.",
    sommelier: "Polished and immediate — a favourite with the grill menu.",
  },
  {
    id: "w-caymus-21",
    producer: "Caymus Vineyards",
    name: "Cabernet Sauvignon",
    vintage: 2021,
    region: "Napa Valley",
    country: "United States",
    grape: "Cabernet Sauvignon",
    bottleSize: "750ml",
    price: 430000,
    costPrice: 300000,
    quantity: 18,
    reorderAt: 6,
    storage: "Cellar · Bay E2",
    supplier: "New World Cellars",
    collections: ["New World"],
    pairing: "Burgers, barbecue, roast beef, aged cheddar.",
    tasting: "Ripe cassis, vanilla and cocoa; plush and warming.",
    sommelier: "Crowd-pleasing and generous; excellent by the glass.",
  },
  {
    id: "w-chard-napa-22",
    producer: "Far Niente",
    name: "Estate Chardonnay",
    vintage: 2022,
    region: "Napa Valley",
    country: "United States",
    grape: "Chardonnay",
    bottleSize: "750ml",
    price: 320000,
    costPrice: 220000,
    quantity: 16,
    reorderAt: 6,
    storage: "Cellar · Bay E4 (white)",
    supplier: "New World Cellars",
    collections: ["New World"],
    pairing: "Grilled prawns, roast chicken, creamy pasta.",
    tasting: "Yellow apple, lemon curd and toasted almond.",
    sommelier: "Rounder than the Meursault, and a fine poolside white.",
  },
];

export const wineById = (id: string) => wines.find((w) => w.id === id);

export function wineStockLabel(quantity: number, reorderAt: number) {
  if (quantity <= 0) return "Out of stock" as const;
  if (quantity <= reorderAt) return "Low stock" as const;
  return "In stock" as const;
}
